const Case = require('../models/Case');
const Notification = require('../models/Notification');
const User = require('../models/User');
const mongoose = require('mongoose');

// @desc    Create new case
// @route   POST /api/cases
exports.createCase = async (req, res) => {
  try {
    // Add the user ID to the case data
    const caseData = {
      ...req.body,
      user: req.user.id,
      status: 'submitted',
      statusHistory: [{
        status: 'submitted',
        changedBy: req.user.id,
        timestamp: new Date(),
        notes: 'Case submitted by user'
      }]
    };

    // Ensure amountLost is a number
    if (caseData.amountLost) {
      caseData.amountLost = parseFloat(caseData.amountLost);
    }

    // Ensure transactionIds is an array
    if (typeof caseData.transactionIds === 'string') {
      caseData.transactionIds = caseData.transactionIds
        .split('\n')
        .map(id => id.trim())
        .filter(id => id.length > 0);
    }

    // Create the case (caseId will be auto-generated by the pre-save hook)
    const newCase = await Case.create(caseData);

    // Populate user info
    await newCase.populate('user', 'name email');

    // Create notification for the user
    await Notification.create({
      user: req.user.id,
      title: 'Case Submitted Successfully',
      message: `Your case "${newCase.title}" has been submitted and is under review. Case ID: ${newCase.caseId}`,
      type: 'case_update',
      relatedCase: newCase._id,
      priority: 'normal'
    });

    // Notify all investigators about new case
    const investigators = await User.find({ role: 'investigator', status: 'active' });
    for (const investigator of investigators) {
      await Notification.create({
        user: investigator._id,
        title: 'New Case Submitted',
        message: `New case "${newCase.title}" (${newCase.caseId}) requires attention.`,
        type: 'case_update',
        relatedCase: newCase._id,
        priority: 'high'
      });
    }

    // Emit socket event if available
    const io = req.app.get('io');
    if (io) {
      io.emit('new_case', { caseId: newCase._id, caseIdStr: newCase.caseId });
    }

    res.status(201).json({
      success: true,
      data: newCase,
      message: 'Case created successfully'
    });
  } catch (error) {
    console.error('Case creation error:', error);
    
    // Handle validation errors
    if (error.name === 'ValidationError') {
      const messages = Object.values(error.errors).map(err => err.message);
      return res.status(400).json({
        success: false,
        message: 'Validation Error',
        errors: messages
      });
    }

    res.status(500).json({
      success: false,
      message: 'Server error',
      error: error.message
    });
  }
};

// @desc    Get all cases (with filters)
// @route   GET /api/cases
exports.getCases = async (req, res) => {
  try {
    let query;

    // For regular users, only show their own cases
    if (req.user.role === 'user') {
      query = Case.find({ user: req.user.id });
    } else {
      query = Case.find({});
    }

    // Apply filters
    if (req.query.status) {
      query = query.where('status').equals(req.query.status);
    }
    if (req.query.fraudType) {
      query = query.where('fraudType').equals(req.query.fraudType);
    }
    if (req.query.riskLevel) {
      query = query.where('riskLevel').equals(req.query.riskLevel);
    }
    if (req.query.search) {
      query = query.or([
        { title: { $regex: req.query.search, $options: 'i' } },
        { caseId: { $regex: req.query.search, $options: 'i' } }
      ]);
    }

    // Sort
    const sortField = req.query.sort || '-createdAt';
    query = query.sort(sortField);

    // Pagination
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 10;
    const skip = (page - 1) * limit;

    const total = await Case.countDocuments(query._conditions || {});
    
    query = query.skip(skip).limit(limit);
    query = query.populate('user', 'name email').populate('assignedInvestigator', 'name email');

    const cases = await query;

    res.status(200).json({
      success: true,
      count: cases.length,
      total,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit)
      },
      data: cases
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Server error',
      error: error.message
    });
  }
};

// @desc    Get single case
// @route   GET /api/cases/:id
exports.getCase = async (req, res) => {
  try {
    const caseData = await Case.findById(req.params.id)
      .populate('user', 'name email phone country')
      .populate('assignedInvestigator', 'name email');

    if (!caseData) {
      return res.status(404).json({
        success: false,
        message: 'Case not found'
      });
    }

    // Check if user is authorized to view this case
    if (req.user.role === 'user' && caseData.user._id.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to view this case'
      });
    }

    res.status(200).json({
      success: true,
      data: caseData
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Server error',
      error: error.message
    });
  }
};

// @desc    Update case
// @route   PUT /api/cases/:id
exports.updateCase = async (req, res) => {
  try {
    let caseData = await Case.findById(req.params.id);

    if (!caseData) {
      return res.status(404).json({
        success: false,
        message: 'Case not found'
      });
    }

    // Check authorization
    if (req.user.role === 'user' && caseData.user.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to update this case'
      });
    }

    // Track who made the change
    caseData._modifiedBy = req.user.id;

    // Update fields
    const allowedFields = [
      'title', 'description', 'amountLost', 'currency', 'country',
      'fraudCompanyName', 'fraudWebsite', 'incidentDate',
      'suspectWallet', 'suspectBankAccount', 'suspectEmail', 'suspectPhone',
      'transactionIds', 'tags'
    ];

    // Investigators and admins can update more fields
    if (req.user.role === 'investigator' || req.user.role === 'admin') {
      allowedFields.push('status', 'riskLevel', 'priority', 'assignedInvestigator', 'resolution');
      caseData._statusNotes = req.body.statusNotes || '';
    }

    allowedFields.forEach(field => {
      if (req.body[field] !== undefined) {
        caseData[field] = req.body[field];
      }
    });

    await caseData.save();

    // Notify user about case update
    if (caseData.user.toString() !== req.user.id) {
      await Notification.create({
        user: caseData.user,
        title: 'Case Updated',
        message: `Your case "${caseData.title}" has been updated.`,
        type: 'case_update',
        relatedCase: caseData._id
      });
    }

    res.status(200).json({
      success: true,
      data: caseData
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Server error',
      error: error.message
    });
  }
};

// @desc    Get case statistics
// @route   GET /api/cases/stats
exports.getCaseStats = async (req, res) => {
  try {
    // Filter by user if not admin/investigator
    const filter = (req.user.role === 'admin' || req.user.role === 'investigator') 
      ? {} 
      : { user: new mongoose.Types.ObjectId(req.user.id) };

    const stats = await Case.aggregate([
      { $match: filter },
      {
        $group: {
          _id: null,
          totalCases: { $sum: 1 },
          totalAmountLost: { $sum: '$amountLost' },
          averageAmount: { $avg: '$amountLost' },
          resolvedCases: {
            $sum: {
              $cond: [{ $in: ['$status', ['resolved', 'closed']] }, 1, 0]
            }
          },
          activeInvestigations: {
            $sum: {
              $cond: [
                { $in: ['$status', ['submitted', 'under_review', 'evidence_verification', 'investigation']] },
                1,
                0
              ]
            }
          }
        }
      }
    ]);

    res.status(200).json({
      success: true,
      data: {
        overview: stats[0] || {
          totalCases: 0,
          totalAmountLost: 0,
          averageAmount: 0,
          resolvedCases: 0,
          activeInvestigations: 0
        }
      }
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Server error',
      error: error.message
    });
  }
};

// @desc    Get user's own case statistics
// @route   GET /api/cases/my-stats
exports.getUserStats = async (req, res) => {
  try {
    const userId = req.user.id;

    const totalCases = await Case.countDocuments({ user: userId });
    const activeCases = await Case.countDocuments({
      user: userId,
      status: { $in: ['submitted', 'under_review', 'evidence_verification', 'investigation'] }
    });
    const resolvedCases = await Case.countDocuments({
      user: userId,
      status: { $in: ['resolved', 'closed'] }
    });
    const pendingReview = await Case.countDocuments({ user: userId, status: 'submitted' });
    const inProgress = await Case.countDocuments({
      user: userId,
      status: { $in: ['under_review', 'evidence_verification', 'investigation'] }
    });

    const amountStats = await Case.aggregate([
      { $match: { user: new mongoose.Types.ObjectId(userId) } },
      { $group: { _id: null, total: { $sum: '$amountLost' } } }
    ]);

    res.status(200).json({
      success: true,
      data: {
        total: totalCases,
        active: activeCases,
        resolved: resolvedCases,
        pending: pendingReview,
        inProgress: inProgress,
        totalAmountLost: amountStats[0]?.total || 0
      }
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Server error',
      error: error.message
    });
  }
};

// Add these to your existing caseController.js

// @desc    Assign investigator to case
// @route   PUT /api/cases/:id/assign
exports.assignInvestigator = async (req, res) => {
  try {
    const { investigatorId } = req.body;
    
    if (!investigatorId) {
      return res.status(400).json({
        success: false,
        message: 'Please provide investigator ID'
      });
    }

    const caseData = await Case.findById(req.params.id);

    if (!caseData) {
      return res.status(404).json({
        success: false,
        message: 'Case not found'
      });
    }

    // Verify investigator exists and has correct role
    const investigator = await User.findById(investigatorId);
    if (!investigator || !['investigator', 'admin'].includes(investigator.role)) {
      return res.status(400).json({
        success: false,
        message: 'Invalid investigator'
      });
    }

    // Assign investigator
    caseData.assignedInvestigator = investigatorId;
    
    // Add to status history
    caseData.statusHistory.push({
      status: caseData.status,
      changedBy: req.user.id,
      timestamp: new Date(),
      notes: `Investigator ${investigator.name} assigned to case`
    });

    // If case is submitted, move to under_review
    if (caseData.status === 'submitted') {
      caseData.status = 'under_review';
      caseData.statusHistory.push({
        status: 'under_review',
        changedBy: req.user.id,
        timestamp: new Date(),
        notes: 'Case moved to under review after investigator assignment'
      });
    }

    await caseData.save();

    // Populate for response
    await caseData.populate('assignedInvestigator', 'name email');
    await caseData.populate('user', 'name email');

    // Notify the investigator
    await Notification.create({
      user: investigatorId,
      title: 'New Case Assigned',
      message: `You have been assigned to case "${caseData.title}" (${caseData.caseId})`,
      type: 'case_update',
      relatedCase: caseData._id,
      priority: 'high'
    });

    // Notify the user
    await Notification.create({
      user: caseData.user,
      title: 'Investigator Assigned',
      message: `${investigator.name} has been assigned to your case "${caseData.title}"`,
      type: 'case_update',
      relatedCase: caseData._id
    });

    res.status(200).json({
      success: true,
      data: caseData,
      message: 'Investigator assigned successfully'
    });
  } catch (error) {
    console.error('Assign investigator error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error',
      error: error.message
    });
  }
};

// @desc    Update case status
// @route   PUT /api/cases/:id/status
exports.updateCaseStatus = async (req, res) => {
  try {
    const { status, notes } = req.body;

    if (!status) {
      return res.status(400).json({
        success: false,
        message: 'Please provide status'
      });
    }

    // Validate status
    const validStatuses = [
      'submitted', 'under_review', 'evidence_verification',
      'investigation', 'escalated', 'resolved', 'closed'
    ];

    if (!validStatuses.includes(status)) {
      return res.status(400).json({
        success: false,
        message: 'Invalid status'
      });
    }

    const caseData = await Case.findById(req.params.id);

    if (!caseData) {
      return res.status(404).json({
        success: false,
        message: 'Case not found'
      });
    }

    // Check authorization
    if (req.user.role === 'user' && caseData.user.toString() !== req.user.id) {
      return res.status(403).json({
        success: false,
        message: 'Not authorized to update this case'
      });
    }

    // Update status
    const oldStatus = caseData.status;
    caseData.status = status;
    
    // Add to status history
    caseData.statusHistory.push({
      status: status,
      changedBy: req.user.id,
      timestamp: new Date(),
      notes: notes || `Status changed from ${oldStatus} to ${status}`
    });

    await caseData.save();

    // Notify the user about status change
    await Notification.create({
      user: caseData.user,
      title: 'Case Status Updated',
      message: `Your case "${caseData.title}" status changed from ${oldStatus.replace(/_/g, ' ')} to ${status.replace(/_/g, ' ')}`,
      type: 'case_update',
      relatedCase: caseData._id
    });

    // Also notify investigator if assigned
    if (caseData.assignedInvestigator && caseData.assignedInvestigator.toString() !== req.user.id) {
      await Notification.create({
        user: caseData.assignedInvestigator,
        title: 'Case Status Updated',
        message: `Case "${caseData.title}" status changed to ${status.replace(/_/g, ' ')}`,
        type: 'case_update',
        relatedCase: caseData._id
      });
    }

    res.status(200).json({
      success: true,
      data: caseData,
      message: 'Case status updated successfully'
    });
  } catch (error) {
    console.error('Update status error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error',
      error: error.message
    });
  }
};